#version 430

layout (local_size_x=10, local_size_y=10) in;
layout (rgba32f, binding=0) uniform image2D img_output;


void main() {
	
    vec4 pixel = (gl_WorkGroupID.x + gl_WorkGroupID.y) %2 == 0 ? 
    	vec4(0, 0.5, 1, 1) :
    	vec4(1, 0.5, 0, 1);
	
	ivec2 coords = ivec2( gl_WorkGroupID.xy ) * 10 + ivec2( gl_LocalInvocationID.xy );
	//ivec2 coords = ivec2( gl_GlobalInvocationID.xy );
	
	
	imageStore(img_output, coords, pixel);
	
	
}